### ISSUE TITLE
Can emq_kafka_bridge use in emqx(emq3.0)

### ISSUE THREAD

**Issue by huangguozhen** [iotblue/emqx-kafka-bridge#17]

**Comment by iotblue** [comment]
Currently emq_kafka_bridge supports emq 2.0, and it's on our road map to support emq 3.0 and there is no time estimate for now

**Comment by onlylivi** [comment]
can emq_kafka_bridge support kafka cluster

**Comment by iotblue** [comment]
Now Kafka bridge support (EMQX 3.0) pleaser refer to EMQX 3.0 branch  https://github.com/iotblue/emqx-kafka-bridge/tree/emqx30 
solved in this commet bf54cdab1bebd8ed78b4e083a227aa4612088d17
